on:
  push:
    branches:
      - "test/windows_ci_build"

name: "Windows Build Test"

jobs:
  build:
    name: "Build Windows"
    runs-on: "windows-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: "Setup stable toolchain"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          profile: "minimal"
          override: true

      - name: "Install cross"
        run: |
          cargo install --locked --version 0.2.5 cross

      - name: "Build release"
        run: |
          cross build --release --target x86_64-pc-windows-msvc
